In [1]:
import pandas as pd
import numpy as np 
import io
#import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [3]:
dataset = pd.read_excel('Bank_Personal_Loan_Modelling 1.xlsx')
dataset.head()

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [4]:
dataset = dataset.drop(['ID', 'ZIP Code'], axis = 1)
dataset.head()

Age  Experience  Income  Family  CCAvg  Education  Mortgage  Personal Loan  \
0   25           1      49       4    1.6          1         0              0   
1   45          19      34       3    1.5          1         0              0   
2   39          15      11       1    1.0          1         0              0   
3   35           9     100       1    2.7          2         0              0   
4   35           8      45       4    1.0          2         0              0   

   Securities Account  CD Account  Online  CreditCard  
0                   1           0       0           0  
1                   1           0       0           0  
2                   0           0       0           0  
3                   0           0       0           0  
4                   0           0       0           1

In [5]:
dataset.head()

Age  Experience  Income  Family  CCAvg  Education  Mortgage  Personal Loan  \
0   25           1      49       4    1.6          1         0              0   
1   45          19      34       3    1.5          1         0              0   
2   39          15      11       1    1.0          1         0              0   
3   35           9     100       1    2.7          2         0              0   
4   35           8      45       4    1.0          2         0              0   

   Securities Account  CD Account  Online  CreditCard  
0                   1           0       0           0  
1                   1           0       0           0  
2                   0           0       0           0  
3                   0           0       0           0  
4                   0           0       0           1

In [6]:
dataset.tail()

Age  Experience  Income  Family  CCAvg  Education  Mortgage  \
4995   29           3      40       1    1.9          3         0   
4996   30           4      15       4    0.4          1        85   
4997   63          39      24       2    0.3          3         0   
4998   65          40      49       3    0.5          2         0   
4999   28           4      83       3    0.8          1         0   

      Personal Loan  Securities Account  CD Account  Online  CreditCard  
4995              0                   0           0       1           0  
4996              0                   0           0       1           0  
4997              0                   0           0       0           0  
4998              0                   0           0       1           0  
4999              0                   0           0       1           1

In [7]:
dataset.shape

(5000, 12)

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
Age                   5000 non-null int64
Experience            5000 non-null int64
Income                5000 non-null int64
Family                5000 non-null int64
CCAvg                 5000 non-null float64
Education             5000 non-null int64
Mortgage              5000 non-null int64
Personal Loan         5000 non-null int64
Securities Account    5000 non-null int64
CD Account            5000 non-null int64
Online                5000 non-null int64
CreditCard            5000 non-null int64
dtypes: float64(1), int64(11)
memory usage: 468.8 KB


In [9]:
for col in dataset.columns:
  length = len(dataset[col].unique())
  print("The unique values in " + str(col) + ":" )
  print(length)


The unique values in Age:
45
The unique values in Experience:
47
The unique values in Income:
162
The unique values in Family:
4
The unique values in CCAvg:
108
The unique values in Education:
3
The unique values in Mortgage:
347
The unique values in Personal Loan:
2
The unique values in Securities Account:
2
The unique values in CD Account:
2
The unique values in Online:
2
The unique values in CreditCard:
2


In [10]:
# Number of people with zero mortgage?
len(dataset[dataset['Mortgage'] == 0])

3462

In [12]:
#Number of people with zero credit card spending per month?
len(dataset[dataset['CCAvg'] == 0])

106

In [13]:
x = dataset.iloc[:, :7]
x.shape

(5000, 7)

In [15]:
y = dataset.iloc[:, 7]
y.shape

(5000,)

In [16]:
# Number of people with zero mortgage?
len(x[x['Mortgage'] == 0])

3462

In [17]:
#Number of people with zero credit card spending per month?
len(dataset[dataset['CreditCard'] == 0])

3530

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(x)
x = sc.transform(x)
x.shape

(5000, 7)

In [19]:
y = dataset.iloc[:, 7]
y.shape

(5000,)

In [20]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3,
                                                    random_state = 0) 

In [21]:
x_train.shape

(3500, 7)

In [22]:
x_test.shape

(1500, 7)

In [23]:
y_train.shape

(3500,)

In [24]:
y_test.shape

(1500,)

In [25]:
from sklearn.linear_model import LogisticRegression

In [26]:
log_r = LogisticRegression()

In [27]:
log_r.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [28]:
pred = log_r.predict(x_test)
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [29]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 

In [45]:
accuracy_score(y_test, pred)*100

95.39999999999999

In [46]:
confusion_matrix(y_test, pred)

array([[1353,   19],
       [  50,   78]], dtype=int64)

In [47]:
classification_report(y_test, pred, target_names=['yes', 'no'])

'              precision    recall  f1-score   support\n\n         yes       0.96      0.99      0.98      1372\n          no       0.80      0.61      0.69       128\n\n    accuracy                           0.95      1500\n   macro avg       0.88      0.80      0.83      1500\nweighted avg       0.95      0.95      0.95      1500\n'

In [48]:
log_r.predict([[26, 20, 50, 3, 1.3, 2, 78], [56, 40, 60, 3, 1.6, 4, 150],
              [0, 0 , 0 , 0, 0, 0, 0]])

array([1, 1, 0], dtype=int64)

In [38]:
from sklearn.metrics import accuracy_score, r2_score, log_loss, classification_report, f1_score
from sklearn.metrics import mean_absolute_error, precision_score,recall_score, roc_auc_score, auc, roc_curve
from sklearn.metrics import mean_squared_error, precision_recall_curve
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB 
model = GaussianNB() 
model.fit(x_train,y_train)


GaussianNB(priors=None)

In [39]:
y_pred = model.predict(x_test)

In [43]:
print("MAE:",metrics.mean_absolute_error(y_test,y_pred)) 
print("R2 score:",metrics.r2_score(y_test,y_pred)) 
print("Accuracy score for test data",metrics.accuracy_score(y_test,y_pred))
print("Accuracy score for train data",metrics.accuracy_score(y_train,model.predict(x_train)))

NameError: name 'metrics' is not defined